version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: Installing NPM
          command: npm install
      - run:
          name: Running eshop tests
          command: npm run test
      - run:
          name: Building eshop application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Ansible and Boto 
          command: pip3 install ansible boto boto3
      - add_ssh_keys:
         fingerprints:
          - "64:aa:3c:b0:28:c0:51:12:ce:f9:02:e3:b0:25:ea:46:16:a3:c9:2a" #AWS SSH key fingerprint
      - run: 
          name: Adding permissions to SSH key file
          command: chmod 400 ansible/secret.pem
      - run:
          name: Persisting password to a file 
          command: echo $ANSIBLE_PASS > .ansible_password.txt
      - run:
          name: List content
          command: ls -la
      - run:
          name: Invoking ansible playbook
          command: ansible-playbook ansible/deploy.yml --user ubuntu --key-file ansible/secret.pem --vault-pass-file .ansible_password.txt
          no_output_timeout: 30m
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
      - run:
          name: Deleting ansible password file
          command: rm .ansible_password.txt
          
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
